/*[% EDSLANG = { 
    home_breadcrumb    									= 'الرئيسية'
	eds_results_TT_no_results   						= 'لايوجد نتائج بحث!'
	eds_results_TT_results_returned_msg					= 'Your search returned'
    eds_results_TT_results_msg							= 'النتائج.'
    eds_results_TT_did_you_mean							= 'هل تعني:'
    eds_results_TT_title_attr							= 'عرض تفاصيل لهذا العنوان'
    eds_results_TT_links								= 'الروابط'
    eds_results_TT_links_html							= 'HTML النص الكامل'
    eds_results_TT_links_pdf							= 'PDF النص الكامل'
    eds_results_TT_links_ebook							= 'eBook النص الكامل'
    eds_results_TT_actions								= ': الإجراءات'
    eds_results_TT_place_reserve						= 'حجز مكان'
    eds_results_TT_save_to_list							= 'حفظ في القوائم'
    eds_results_TT_in_cart								= 'في سلة التسوق'
    eds_results_TT_remove_cart							= '(حذف)'
    eds_results_TT_add_cart								= 'اضف إلى سلة التسوق'
	eds_results_TT_login_msg							= 'تسجيل الدخول للوصول إلى النتائج'
    eds_results_TT_annosuggestions						= 'لم يتم العثور على ما تبحث عنه?'
    eds_results_TT_annosuggestions_makea				= 'انشئ'
    eds_results_TT_annosuggestions_purchase				= 'اقتراح شراء'
    
	eds_detail_TT_details_for							= 'مزيد من التفاصيل عن'
	eds_detail_TT_normal_view							= 'العرض العادي'
	eds_detail_TT_login_msg								= 'تسجيل الدخول للوصول إلى النتائج'
    
    eds_detail_customlinks_INC_html_fulltext			= 'HTML النص الكامل'
    eds_detail_customlinks_INC_pdf_fulltext				= 'PDF النص الكامل'
    eds_detail_customlinks_INC_ebook_fulltext			= 'eBook النص الكامل'
    eds_detail_customlinks_INC_view_in_eds				= 'EDS المشاهدة في'
    
    eds_detail_sidebar_INC_print						= 'طباعة'
    eds_detail_sidebar_INC_in_cart						= 'اضف إلى سلة التسوق'
    eds_detail_sidebar_INC_remove_cart					= '(حذف)'
    eds_detail_sidebar_INC_add_cart						= 'اضف إلى سلة التسوق'
        
	eds_advsearch_TT_breadcrumb_home					= 'الرئيسية'
    eds_advsearch_TT_breadcrumb_advanced_search			= 'البحث المتقدم'
    eds_advsearch_TT_select_field						= 'حدد حقل (اختياري)'
	eds_advsearch_TT_bool_and							= 'و'
	eds_advsearch_TT_bool_or							= ' أو'
	eds_advsearch_TT_bool_not							= 'لا'
    eds_advsearch_TT_opt_add							= 'إضافة'
    eds_advsearch_TT_opt_remove							= 'حذف'
    eds_advsearch_TT_search_options						= 'خيارات البحث'
    eds_advsearch_TT_search_opt_heading					= 'وسائل البحث مفصلة'
    eds_advsearch_TT_search_opt_modes					= 'وسائط البحث'
    eds_advsearch_TT_search_help_title					= 'EBDCO رية النصوص للبحث سواء كانت عبارة أو جملة أو فقرة أو صفحة كاملة سيتم البحث قي بنك المعلومات ل '
    eds_advsearch_TT_search_help						= 'تلميح'
    eds_advsearch_TT_limit_legend						= 'الحد من النتائج الخاصة بك'
	eds_advsearch_TT_date_month							= 'الشهر'
	eds_advsearch_TT_date_month_jan						=  'يناير'
    eds_advsearch_TT_date_month_feb						= 'فبراير'
    eds_advsearch_TT_date_month_mar						= 'مارس'
    eds_advsearch_TT_date_month_apr						= 'أبريل'
    eds_advsearch_TT_date_month_may						= 'مايو'
    eds_advsearch_TT_date_month_jun						= 'يونيو'
    eds_advsearch_TT_date_month_jul						= 'يوليو'
    eds_advsearch_TT_date_month_aug						= 'أغسطس'
    eds_advsearch_TT_date_month_sep						= 'سبتمبر'
    eds_advsearch_TT_date_month_oct						= 'أكتوبر'
    eds_advsearch_TT_date_month_nov						= 'نوفمبر'
    eds_advsearch_TT_date_month_dec						= 'ديسمبر'
    eds_advsearch_TT_date_year							= 'السنة'
    eds_advsearch_TT_btn_search							= 'بحث'
    eds_advsearch_TT_btn_reset							= 'إعادة تعيين'
    

    
    eds_facets_INC_refine_search						= 'تفصيل البحث'
    eds_facets_INC_current_search						= 'البحث الحالي'
	eds_facets_INC_search_term							= 'مصطلحات البحث'
    eds_facets_INC_active_facets						= 'Active Facets'
    eds_facets_INC_limit_to								= 'الحد إلى'
    eds_facets_INC_expand_to							= 'توسيع إلى'
    
    eds_page_numbers_INC_previous						= 'السابقة'
    eds_page_numbers_INC_next 							= 'التالي'
    
    eds_publicationexactmatch_INC_full_text_access		= 'الوصول إلى النص الكامل'
    eds_publicationexactmatch_INC_search_within			= 'البحث داخل المنشور'
    
    eds_researchstarters_INC_more						= 'أكثر'
    
    eds_resort_form_INC_results_per_page				= 'النتائج في الصفحة الواحدة'
    eds_resort_form_INC_view							= 'طريقة العرض'
    eds_resort_form_INC_view_title						= 'العنوان'
    eds_resort_form_INC_view_brief						= 'موجز'
    eds_resort_form_INC_view_detail						= 'مفصلة'
    eds_resort_form_INC_search_mode						= 'وضع البحث'
    eds_resort_form_INC_sort_by							= 'الترتيب حسب'
}%]*/
var EDSLANG = {
	eds_koha_lang_id									: 'افتراضي',
	eds_koha_language									: '[%lang%]',
	eds_switch_text										: 'قم بالتبديل إلى اكتشاف',
	koha_switch_text									: 'قم بالتبديل إلى الفهرس',
	eds_select_text										: "اكتشاف",
	eds_select_info										: '<h3> بحث EDS<h3>قم بتحديد عنصر معروف وأدخل مصطلح البحث',
	koha_select_info									: '<h3>بحث Koha</h3>قم بتحديد عنصر معروف وأدخل مصطلح البحث',
	search_breadcrumb									: 'نتائج البحث',
	pfi_atoz_bar										: 'استعراض حسب سجلات العناوين',
	login_to_access										: 'تسجيل الدخول للوصول إلى هذه النتيجة',
	go_to_detail										: 'اذهب إلى التفاصيل',
	more_details										: 'مزيد من النتائج',
	view_more_results									: 'عرض مزيد من النتائج',
	more_loading_msg									: 'تحميل. الرجاء الانتظار'
	previous_title										: 'انظر السابق',
	previous											: 'السابق',
	next_title											: 'انظر التالية',
	next												: 'التالي',
	update_facets										: 'تعديل',
	basket_loading										: 'تحميل العناصر. الرجاء الانتظار',
	basket_item_location								: "اكتشاف",
	basket_deselect_hold								: 'إلغاء تحديد عناوين لعدم حجز مكان',
	basket_deselect_list								: 'إلغاء تحديد عناوين لعدم الإضافة إلى القائمة',
	date_valid_format									: 'YYYY الرجاء إدخال سنة بالصيغة ',
	date_invalid										: ' إزالة كافة الأحرف واضغط  انتر لإزالة محدد التاريخ. YYYY-MM صيغة التاريخ ' 
						
};